# Generated by Django 6.0.2 on 2026-02-09 09:47

import django.core.validators
import django.utils.timezone
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('games', django_mongodb_backend.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True)),
                ('filter_json', models.JSONField(blank=True, default=dict)),
                ('pool_limit', models.IntegerField(default=20)),
                ('sort_by', models.CharField(choices=[('popular', 'Popularity'), ('rating', 'Rating'), ('new', 'Release date')], default='popular', max_length=40)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('_id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('ranking_date', models.DateField(default=django.utils.timezone.now)),
                ('categoryCode', models.IntegerField()),
                ('rating', django_mongodb_backend.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True)),
            ],
            options={
                'db_table': 'rankings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('_id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255)),
                ('videoGameCode', models.IntegerField()),
                ('reviewDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('first_release_date', models.CharField(max_length=255)),
                ('platforms', models.CharField(blank=True, max_length=255, null=True)),
                ('developers', models.CharField(max_length=255, null=True)),
                ('publishers', models.CharField(blank=True, max_length=255, null=True)),
                ('genres', models.CharField(blank=True, max_length=255, null=True)),
                ('total_rating', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_rating_count', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cover_id', models.IntegerField(blank=True, null=True)),
                ('cover_url', models.CharField(blank=True, max_length=255, null=True)),
                ('categories', django_mongodb_backend.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True)),
            ],
            options={
                'db_table': 'videogames',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('role', models.IntegerField(choices=[(1, 'Admin'), (2, 'Client')])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
